title: My Favorite Blog
author: Rodrigo
email: rodrigo.dev@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hi there this is a type of blog where we can talk about some interesting things about
  programming world and also about our personal life. 
  Note: This is a practice website
# social links
twitter_username: null # DO NOT include the @ character, or else the build will fail!
github_username:  rodrigo # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
# theme
theme: minima
